[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
IncompleteLU = "40713840-3770-5561-ab4c-a76e7d0d7895"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
MatrixMarket = "4d4711f2-db25-561a-b6b3-d35e7d4047d3"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
