[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
